r: 64
lora_alpha: 64
lora_dropout: 0.2
target_modules:
  - "q_proj"
  - "k_proj"
  - "v_proj"
  - "o_proj"
  - "gate_proj"
  - "up_proj"
  - "down_proj"
bias: "none"
init_lora_weights: true # "gaussian"
use_dora: false
use_rslora: false

