# KANANA1_5_IT_8B = "kakaocorp/kanana-1.5-8b-instruct-2505"
# KANANA1_5_BASE_8B = "kakaocorp/kanana-1.5-8b-base"

model_id: "kakaocorp/kanana-1.5-8b-base"
dtype: "fp16"
# use_flash_attention: true

# only train
early_stopping: 5 # or null
early_stopping_threshold: 0.001 # or null

# only test
max_new_tokens: 2048
do_sample: false

