source_files:
  - "data/rag/corpus.pdf"
style: "kowiki" # pdf kowiki
output_dir: "data/rag_results"
index_dir: "data/rag_results/index"
chunk_size: 100
chunk_overlap: 5
min_last_chunk_ratio: 0.2
model_id: "nlpai-lab/KURE-v1"
top_k: 3
retriever_type: "dense" # dense, hybrid, bm25
hybrid_alpha: 0.5
context_text: "[관련 정보]"
context_field: "retrieved_context"
index_name: "index.faiss"
corpus_name: "corpus.json"
batch_size: 32
use_rag: false

