is_train: true
additional_info: ""
seed: 42
hf_token: ""
use_lora: true
use_qlora: false
data_raw_dir: "data/other/task_3_merged_1-3_c1"
data_rag_dir: "data/rag"

prompt_version: "task3"


# only test
save_dir: "" # it will be set by the function
adapter_dir: "lora_adapter" # it will be set by the function
test_result_dir: "test_results"
